# Generated by Django 3.0.6 on 2020-05-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=256)),
                ('polarity', models.DecimalField(decimal_places=2, max_digits=64)),
                ('subjectivity', models.DecimalField(decimal_places=2, max_digits=64)),
                ('mentions', models.CharField(max_length=256)),
                ('hashtags', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('route', models.CharField(max_length=256)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=64)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=64)),
                ('conditions', models.CharField(max_length=256)),
            ],
        ),
    ]
