# Generated by Django 3.0.6 on 2020-05-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetobject',
            name='conditions',
        ),
        migrations.AlterField(
            model_name='tweetobject',
            name='date',
            field=models.CharField(max_length=256),
        ),
    ]
