# Generated by Django 3.0.6 on 2020-05-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0002_auto_20200531_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetobject',
            name='conditions',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tweetobject',
            name='hashtags',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tweetobject',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=64),
        ),
        migrations.AlterField(
            model_name='tweetobject',
            name='location',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tweetobject',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=64),
        ),
        migrations.AlterField(
            model_name='tweetobject',
            name='mentions',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tweetobject',
            name='route',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
