# Generated by Django 3.0.6 on 2020-05-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0003_auto_20200531_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetobject',
            name='polarity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tweetobject',
            name='subjectivity',
            field=models.FloatField(),
        ),
    ]
