# Generated by Django 3.0.6 on 2020-05-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0005_auto_20200531_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetobject',
            name='conditions',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
