# Generated by Django 3.0.6 on 2020-06-03 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0006_auto_20200531_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetobject',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
